name: GestureKeys
options:
  bundleIdPrefix: com.gesturekeys
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "5"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  GestureKeys:
    type: application
    platform: macOS
    sources:
      - GestureKeys
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.gesturekeys.app
        INFOPLIST_FILE: GestureKeys/Info.plist
        CODE_SIGN_ENTITLEMENTS: GestureKeys/GestureKeys.entitlements
        OTHER_LDFLAGS:
          - "-framework"
          - "MultitouchSupport"
        FRAMEWORK_SEARCH_PATHS:
          - /System/Library/PrivateFrameworks
        SWIFT_VERSION: "5"
        CODE_SIGN_IDENTITY: "-"
        ENABLE_HARDENED_RUNTIME: false
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
